version: "2.1"

services:

  mysql:
    image: mysql:8.0
    restart: "no"
    ports:
      - 3316:3306
    healthcheck:
      test: "/etc/init.d/mysql status"
      timeout: 1s
      retries: 60
    volumes:
      - "./docker/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: p@ssword
      MYSQL_DATABASE: camo

  php:
    build: docker/apache
    tty: true
    ports:
      - "8080:80"
    volumes:
      - "./docker/apache/dev.conf:/etc/apache2/sites-enabled/000-default.conf"
      - ".:/var/www"
    depends_on:
      mysql:
        condition: service_healthy
    env_file: .env