App\Entity\User:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
  properties:
    email:
      - NotBlank: ~
      - Email: ~
    password:
      - NotBlank: ~
    roles:
      - NotBlank: ~
      - Unique: ~